config/routes.rb
Rails.application.routes.draw do
  resources :cashmasters
  root 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashdetail.rb
class Cashdetail < ApplicationRecord
  belongs_to :cashmaster
end

app/models/cashmaster.rb
class Cashmaster < ApplicationRecord
    has_many :cashdetails, dependent: :destroy
    accepts_nested_attributes_for :cashdetails, reject_if: :all_blank, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cashmasters_controller.rb
class CashmastersController < ApplicationController
  before_action :set_cashmaster, only: [:show, :edit, :update, :destroy]

  # GET /cashmasters
  # GET /cashmasters.json
  def index
    @cashmasters = Cashmaster.all
  end

  # GET /cashmasters/1
  # GET /cashmasters/1.json
  def show
  end

  # GET /cashmasters/new
  def new
    @cashmaster = Cashmaster.new
  end

  # GET /cashmasters/1/edit
  def edit
  end

  # POST /cashmasters
  # POST /cashmasters.json
  def create
    @cashmaster = Cashmaster.new(cashmaster_params)

    respond_to do |format|
      if @cashmaster.save
        format.html { redirect_to @cashmaster, notice: 'Cashmaster was successfully created.' }
        format.json { render :show, status: :created, location: @cashmaster }
      else
        format.html { render :new }
        format.json { render json: @cashmaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cashmasters/1
  # PATCH/PUT /cashmasters/1.json
  def update
    respond_to do |format|
      if @cashmaster.update(cashmaster_params)
        format.html { redirect_to @cashmaster, notice: 'Cashmaster was successfully updated.' }
        format.json { render :show, status: :ok, location: @cashmaster }
      else
        format.html { render :edit }
        format.json { render json: @cashmaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cashmasters/1
  # DELETE /cashmasters/1.json
  def destroy
    @cashmaster.destroy
    respond_to do |format|
      format.html { redirect_to cashmasters_url, notice: 'Cashmaster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cashmaster
      @cashmaster = Cashmaster.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cashmaster_params
      params.require(:cashmaster).permit(:name, :price, :comments, 
           cashdetails_attributes:[:id, :itemname, :qty, :rate, :_destroy])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashmasters_helper.rb
module CashmastersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/cashmasters/_cashdetail_fields.html.erb
<div class="nested-fields">
  <div class="field">
  <%= f.label :itemname %>
    <%= f.text_field :itemname %>
  
  <%= f.label :qty %>
    <%= f.number_field :qty %>
  
  <%= f.label :rate %>
     <%= f.number_field :rate %>
  </div> 
  <%= link_to_remove_association "remove task", f %>
</div>





<div class="nested-fields container">
  <div class="row">

        <div class="field col-sm-8  row ">
        <%= f.label :itemname %>
            <%= f.text_field :itemname %>
        
        <%= f.label :qty %> 
            <%= f.number_field :qty %>
        
        <%= f.label :rate %>
            <%= f.number_field :rate %>
        </div> 
        <div class="col-sm-4">
          <%= link_to_remove_association "remove task", f %>'
        </div>
    </div>    
</div>

app/views/cashmasters/_form.html.erb
<%= form_with(model: cashmaster, local: true) do |form| %>
  <% if cashmaster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cashmaster.errors.count, "error") %> prohibited this cashmaster from being saved:</h2>

      <ul>
        <% cashmaster.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, :class => 'text_field' %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments %>
  </div>

  <h3>Add the iteams</h3>

    <%= form.fields_for :cashdetails do |cashdetail| %>
      <%= render 'cashdetail_fields', :f => cashdetail %>
    <% end %>
    <div class="links">
       <%= link_to_add_association 'add Items', form, :cashdetails %>
    </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cashmasters/edit.html.erb
<h1>Editing Cashmaster</h1>

<%= render 'form', cashmaster: @cashmaster %>

<%= link_to 'Show', @cashmaster %> |
<%= link_to 'Back', cashmasters_path %>

app/views/cashmasters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cashmasters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cashmasters.each do |cashmaster| %>
      <tr>
        <td><%= cashmaster.name %></td>
        <td><%= cashmaster.price %></td>
        <td><%= cashmaster.comments %></td>
        <td><%= link_to 'Show', cashmaster %></td>
        <td><%= link_to 'Edit', edit_cashmaster_path(cashmaster) %></td>
        <td><%= link_to 'Destroy', cashmaster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cashmaster', new_cashmaster_path %>

app/views/cashmasters/new.html.erb
<h1>New Cashmaster</h1>

<%= render 'form', cashmaster: @cashmaster %>

<%= link_to 'Back', cashmasters_path %>

app/views/cashmasters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cashmaster.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cashmaster.price %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @cashmaster.comments %>
</p>

<h3>Items list</h3>
<ul>
  <% for @cashdetail in @cashmaster.cashdetails %>
  <li><%= @cashdetail.itemname %></li>
  <li><%= @cashdetail.qty %></li>
  <li><%= @cashdetail.rate %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_cashmaster_path(@cashmaster) %> |
<%= link_to 'Back', cashmasters_path %>

app/views/homes/index.html.erb
<div class="container">
<h1>This is our index page</h1>
<%= link_to "Add new master record", new_cashmaster_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>